[versions]
kaml = "0.102.0"
koin = "4.1.1"
kotlinx-serialization = "1.9.0"

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
